name: balanced_meal
description: "Food Ordering App"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  hooks_riverpod: ^2.6.1
  page_transition: ^2.2.1
  flutter_hooks: ^0.21.2
  url_launcher: ^6.3.1
  equatable: ^2.0.7
  flutter_svg: ^2.2.0
  flutter_keyboard_visibility: ^6.0.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true