// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY3sd8Y2Eg5OkIJZgP-t4VbRVODxycFow',
    appId: '1:958676033067:web:4a528d8d648615a9b8546e',
    messagingSenderId: '958676033067',
    projectId: 'balanced-meal-57',
    authDomain: 'balanced-meal-57.firebaseapp.com',
    storageBucket: 'balanced-meal-57.firebasestorage.app',
    measurementId: 'G-4H2LMTE8M5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9xmf5Qjr3rINCdS4W6OrytY8CqVBL-Dc',
    appId: '1:958676033067:android:08231915b7eb0dd0b8546e',
    messagingSenderId: '958676033067',
    projectId: 'balanced-meal-57',
    storageBucket: 'balanced-meal-57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmTaVlYV7P3OQiNt1pNIM4ZkyrjZxmIjU',
    appId: '1:958676033067:ios:5770efc3315cb6cbb8546e',
    messagingSenderId: '958676033067',
    projectId: 'balanced-meal-57',
    storageBucket: 'balanced-meal-57.firebasestorage.app',
    iosBundleId: 'com.example.balancedMeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmTaVlYV7P3OQiNt1pNIM4ZkyrjZxmIjU',
    appId: '1:958676033067:ios:5770efc3315cb6cbb8546e',
    messagingSenderId: '958676033067',
    projectId: 'balanced-meal-57',
    storageBucket: 'balanced-meal-57.firebasestorage.app',
    iosBundleId: 'com.example.balancedMeal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY3sd8Y2Eg5OkIJZgP-t4VbRVODxycFow',
    appId: '1:958676033067:web:a9d1c41d87e948d3b8546e',
    messagingSenderId: '958676033067',
    projectId: 'balanced-meal-57',
    authDomain: 'balanced-meal-57.firebaseapp.com',
    storageBucket: 'balanced-meal-57.firebasestorage.app',
    measurementId: 'G-LJ8LY5PVE1',
  );
}
